version: 2

models:
  - name: stg_patient_events
    columns:
      - name: patient_id
        tests:
          - not_null
      - name: event_time
        tests:
          - not_null

  - name: patient_journey_summary
    columns:
      - name: patient_id
        tests:
          - not_null
          - unique